Updates config to use right version of drush, adds initial 7.4 config.
drydockcloud/drupal-acquia pull request #15
Opened 2021-07-27 20:04 UTC by synterra

2021-07-27 21:01 UTC, grugnog requested changes
Looks good from a config perspective - I think some extra files were added though. 
We would need to add tests in Jenkinsfile to see if it builds

2021-07-27 21:01 UTC, grugnog commented on getconfig/getconfig.php
> +<?php
I think this was committed by mistake - it lives in it's own repo, so if we need to make changes we should make them there.

2021-07-27 21:01 UTC, grugnog commented on httpd/Dockerfile-e
> +FROM httpd:2.4.18
Are the `-e` files backups?

2021-07-28 12:48 UTC, closed without merging

2021-07-28 12:53 UTC, synterra commented
New PR for this is at https://github.com/drydockcloud/drupal-acquia/pull/16